### ISSUE TITLE
chore: PR 템플릿 생성

### ISSUE THREAD

**Issue by NamJwong** [prgrms-fe-devcourse/FEDC3_POMO_DY#3]
### 들어가야 할 내용
- 어떤 것을 구현했는지 요약/어떻게 구현했는지 설명
- PR Point (우려되는 점, 집중해서 봐주었으면 하는 점 등)
- 구현 결과 스크린샷

**Comment by zerosial** [comment]
실수로 초기 설정이라 생각하고 main에다 바로 작업해버렸습니다.
다음부터 주의할게요 😥

**Comment by NamJwong** [comment]
다시 올려주기로 함!
