### ISSUE TITLE
chore: Issue 템플릿 추가

### ISSUE THREAD

**Issue by zerosial** [prgrms-fe-devcourse/FEDC3_POMO_DY#5]
**추가하려는 잡일의 목적을 적어주세요**
Issue 템플릿을 추가하여 서류 작성의 최소화

**해 주었으면 하는 잡일**
깃허브 셋팅을 통해 Issue 템플릿을 작성해주세요!

**Comment by zerosial** [comment]
실수로 초기 설정이라 생각하고 main에다 바로 작업해버렸습니다.
다음부터 주의할게요 😥

**Comment by NamJwong** [comment]
다시 올려주기로 함!
